name: monipoint_challenge
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:

  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_timer_countdown: ^1.0.7
  get_it: ^8.0.0
  glassmorphism_widgets: ^0.2.2
  go_router: ^14.2.8
  go_router_paths: ^0.2.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  icons_launcher: ^3.0.0
  intl: ^0.19.0
  label_marker: ^1.0.1
  overlay_support: ^2.1.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  toastification: ^2.3.0
  

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/images/Moniepoint-Logo.jpeg"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/env/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Bold.ttf
        - asset: assets/fonts/Sora-ExtraBold.ttf
        - asset: assets/fonts/Sora-ExtraLight.ttf
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-SemiBold.ttf
        - asset: assets/fonts/Sora-Thin.ttf



